crm_project/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView,LogoutView
from django.urls import path, include, reverse
from django.contrib.auth import views as auth_view
from users.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('records.urls')),
    path('',auth_view.LoginView.as_view(template_name='users/loginview.html'),name='login'),
    path('logout/',auth_view.LogoutView.as_view(template_name='users/logoutview.html'),name='logout'),
    path('register/',register,name='register'),
    path('accounts/', include('allauth.urls')),

]

records/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from .views import *

urlpatterns = [
    path('records', RecordListView.as_view(), name='home'),
    path('create/', RecordCreateView.as_view(), name='create'),
    path('update/<int:pk>', RecordUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', RecordDeleteview.as_view(), name='delete'),
    path('record/<int:pk>', RecordDetailView.as_view(), name='details'),
]

records/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class Record(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField()
    country=models.CharField(max_length=50)
    date_created=models.DateTimeField(default=timezone.now)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home')

users/models.py
from django.db import models

# Create your models here.

records/forms.py
from django.forms import ModelForm
from .models import Record

class RecordForm(ModelForm):
    class Meta:
        model=Record
        fields=['name','email','country']

records/views.py
from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView,DeleteView,DetailView,UpdateView,CreateView
from .models import Record
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin

# Create your views here.

# def home(request):
#     return render(request,'records/home.html')

class RecordListView(LoginRequiredMixin,ListView):
    model = Record
    template_name = 'records/home.html'
    paginate_by = 20

    def get_queryset(self):
        user=self.request.user
        return Record.objects.filter(user=user)


class RecordCreateView(LoginRequiredMixin,CreateView):
    model = Record
    fields = ['name','email','country']

    def form_valid(self, form):
        form.instance.user=self.request.user
        return super().form_valid(form)


class RecordUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = Record
    fields = ['name', 'email', 'country']
    template_name = 'records/record_update_form.html'

    def test_func(self):
        record=self.get_object()
        if record.user==self.request.user:
            return True

        return False


class RecordDeleteview(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Record
    success_url ="/"
    def test_func(self):
        record=self.get_object()
        if record.user==self.request.user:
            return True

        return False

class RecordDetailView(LoginRequiredMixin,UserPassesTestMixin,DetailView):
    model = Record
    template_name = 'records/record_detail.html'
    def test_func(self):
        record=self.get_object()
        if record.user==self.request.user:
            return True

        return False

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render,redirect

# Create your views here.

def register(request):
    if request.method=='POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()

    context={
        'form':form
    }

    return render(request,"users/register.html",context)

records/templates/records/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <title>{% block title %}  {% endblock title%}</title>
</head>
<body class="bg-gray-100">
  <header class="bg-white shadow">
    <nav class="container mx-auto px-4 py-2 flex justify-between items-center sticky top-0">
      <h1 class="text-2xl font-semibold"><a href="{% url 'home'%}">CRM</a></h1>
      <ul class="space-x-4">
        <li class="inline-block">
          <a href="{% url 'home' %}" class="text-gray-600 hover:text-gray-800">Records</a>
        </li>
        <li class="inline-block">
          <a href="{% url 'create' %}" class="text-gray-600 hover:text-gray-800">Add</a>
        </li>
          {% if user.is_authenticated %}
              <li class="inline-block">
              <a href="{% url 'logout' %}" class="text-gray-600 hover:text-gray-800">Logout</a>
              </li>
          {% else %}
              <li class="inline-block">
              <a href="{% url 'login' %}" class="text-gray-600 hover:text-gray-800">Login</a>
              </li>
          {% endif %}

      </ul>
    </nav>
  </header>

  <main class="container mx-auto px-4 py-8 ">
  {% block content %}

  {% endblock content %}
  </main>

  <footer class="bg-gray-200 py-4 sticky bottom-0">
    <div class="container mx-auto px-4 text-center">
      <p class="text-gray-600">© 2023 CRM. All rights reserved.</p>
    </div>
  </footer>
</body>
</html>

records/templates/records/home.html
{% extends 'records/base.html' %}
{% block title %}
CRM Records
{% endblock %}

{% block content %}
<div class="bg-white shadow rounded-lg p-4 text-center">
      <h2 class="text-lg font-semibold mb-4">Contact Records</h2>
      <table class="w-2/3 mx-auto">
        <thead>
          <tr class="border-b">
            <th class="py-2">Name</th>
            <th class="py-2">Email</th>
            <th class="py-2">Country</th>
            <th class="py-2">ID</th>
          </tr>
        </thead>
        <tbody>
        {% for record in record_list %}
          <tr class="border-b">
            <td class="py-2">{{ record.name }}</td>
            <td class="py-2">{{ record.email }}</td>
            <td class="py-2">{{ record.country }}</td>
            <td class="py-2"><a class=" text-blue-500" href="{% url 'details' record.id %}"> {{ record.id }}</a></td>
        {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="flex justify-center my-4">
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="?page=1" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">First</a>
            <a href="?page={{ page_obj.previous_page_number }}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Prev</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a href="?page={{ num }}" class="text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 focus:outline-none dark:focus:ring-red-800">{{ num }}</a>
            {% elif page_obj.number|add:'-3' < num and page_obj.number|add:3 > num %}
                <a href="?page={{ num }}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">{{ num }}</a>


            {% endif %}


        {% endfor %}


        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Last</a>

        {% endif %}



    {% endif %}
    </div>
{% endblock %}

records/templates/records/record_confirm_delete.html
{% extends 'records/base.html' %}
{% load tailwind_filters %}
{% block title %}
    Create
{% endblock %}

{% block content %}
<div class="w-full max-w-xs mx-auto ">
  <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" method="post" enctype="multipart/form-data">
    {% csrf_token %}
      <p class="text-3xl">Delete Record for {{ object.id }}</p>
      {{ form|crispy }}
    <div class="flex items-center justify-between">
      <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
        Delete Record
      </button>
    </div>
  </form>

</div>

{% endblock %}

records/templates/records/record_detail.html
{% extends 'records/base.html' %}
{% block title %}
Detail
{% endblock %}
{% block content %}
<div class="bg-white shadow rounded-lg p-4">
      <h2 class="text-3xl font-semibold mb-4">Contact Details for id no {{ object.id }}</h2>
      <div class="space-y-4">
        <div>
          <p class="font-semibold">Name:</p>
          <p class="text-gray-600">{{ object.name}}</p>
        </div>
        <div>
          <p class="font-semibold">Country:</p>
          <p class="text-gray-600">{{ object.country }}</p>
        </div>
        <div>
          <p class="font-semibold">Email:</p>
          <p class="text-gray-600">{{ object.email }}</p>
        </div>
      </div>
<div class="my-6">
<a href="{% url 'update' object.id %}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Update</a>
<a href="{% url 'delete' object.id %}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Delete</a>
</div>
    </div>
{% endblock %}

records/templates/records/record_form.html
{% extends 'records/base.html' %}
{% load tailwind_filters %}
{% block title %}
    Create
{% endblock %}

{% block content %}
<div class="w-full max-w-xs mx-auto ">
  <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" method="post" enctype="multipart/form-data">
    {% csrf_token %}
      <p class="text-3xl">Create Record</p>
      {{ form|crispy }}
    <div class="flex items-center justify-between">
      <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
        Create Record
      </button>
    </div>
  </form>

</div>

{% endblock %}

records/templates/records/record_update_form.html
{% extends 'records/base.html' %}
{% load tailwind_filters %}
{% block title %}
    Update
{% endblock %}

{% block content %}
<div class="w-full max-w-xs mx-auto ">
  <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" method="post" enctype="multipart/form-data">
    {% csrf_token %}
      <p class="text-3xl">Update Record</p>
      {{ form|crispy }}
    <div class="flex items-center justify-between">
      <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
        Update Record
      </button>
    </div>
  </form>

</div>

{% endblock %}

users/templates/users/loginview.html
{% extends 'records/base.html' %}
{% load tailwind_filters %}
{% block title %}
    Create
{% endblock %}

{% block content %}
<div class="w-full max-w-xs mx-auto ">
  <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" method="post" enctype="multipart/form-data">
    {% csrf_token %}
      <p class="text-3xl">Login User</p>
      {{ form|crispy }}
    <div class="flex items-center justify-between">
      <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
        Login
      </button>
    </div>
      <p>Don't have account ? <a href="{% url 'register' %}">Sign Up</a></p>
  </form>

</div>

{% endblock %}

users/templates/users/logoutview.html
{% extends 'records/base.html' %}
{% block title %}
Logged out
{% endblock %}

{% block content %}
<p class="text-2xl mt-4 mx-4">You have Logged out. Want to log in again? <a href="{% url 'login' %}" class="text-blue-500">Login</a></p>
{% endblock %}

users/templates/users/register.html
{% extends 'records/base.html' %}
{% load tailwind_filters %}
{% load socialaccount %}

{% block title %}
    Create
{% endblock %}

{% block content %}
<div class="w-2/3 mx-auto ">
  <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" method="post" enctype="multipart/form-data">
    {% csrf_token %}
      <p class="text-3xl">Register User</p>
      {{ form|crispy }}
    <div class="flex items-center justify-between">
      <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
        Register
      </button>

<a href="{% provider_login_url 'github' %}">Sign Up</a>
<a href="{% provider_login_url 'google' %}">Sign Up Google</a>
    </div>
  </form>

</div>

{% endblock %}